### ISSUE TITLE
Not loading in BBEdit 10.1 (Lion)

### ISSUE THREAD

**Issue by alexkingorg** [rwilcox/bbedit-diff-language-module#2]
This worked great for me previously on another machine, but it doesn't seem to be taking effect in BBEdit 10.1 for me on my new box. I was curious if this is still working for you (indicating it's likely a local issue for me).

Thanks for your time.

**Comment by rwilcox** [comment]
I'll check into this, but I'm mostly sure that I use the same language module in my Git package and (just tested it), it seems to work fine for me...

**Comment by alexkingorg** [comment]
Ok, likely to be a local issue then I presume. Thanks for the note.

**Comment by alexkingorg** [comment]
This was a PEBCAK issue, apologies for wasting your time. Thanks for the response.

**Comment by rwilcox** [comment]
Excellent!
